"""
Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten
pentagonal numbers are:

    1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
difference are pentagonal and D = |Pk - Pj| is minimized; what is the value of
D?

link: https://projecteuler.net/problem=44

Solution:

It is one of the problems where there are no better solutions than brute force.
But we can make one observation. The pentagonal number can be generated by the
formula:

    Pn=n(3n-1)/2

So if the Pn is pentagonal, then the inverse of the formula is:

    3n^2 - n - 2Pn = 0 => n = (sqrt(24*Pn + 1) + 1) / 6

    If (sqrt(24*Pn + 1) + 1) % 6 == 0, then sqrt(24*Pn + 1) % 6 = 5

Let's iterate from k = 2, and for each k, iterate from j = 1 to k. If the
difference and the sum of the pentagonal numbers are pentagonal, then we found
the solution. We can stop the iteration when we found the first solution, since
the difference will be the smallest. We can prove that the first solution will
be the smallest, because the pentagonal numbers are increasing, so the
difference will be increasing too.
"""
import math

from itertools import count


def is_pentagonal(n: int) -> int:
    return math.sqrt(24*n + 1) % 6 == 5


def solution():
    for k in count(2):
        pk = k*(3*k - 1) // 2
        for j in range(1, k):
            pj = j*(3*j - 1) // 2
            if is_pentagonal(pk - pj) and is_pentagonal(pk + pj):
                return abs(pk - pj)


# test
if __name__ == '__main__':
    print(solution())  # 5482660
