"""
Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

    2**2=4,  2**3=8,   2**4=16,  2**5=32
    3**2=9,  3**3=27,  3**4=81,  3**5=243
    4**2=16, 4**3=64,  4**4=256, 4**5=1024
    5**2=25, 5**3=125, 5**4=625, 5**5=3125

If they are then placed in numerical order, with any repeats removed, we get
the following sequence of 15 distinct terms:

    4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 256, 625, 1024, 3125.

How many distinct terms are in the sequence generated by a**b for 2 ≤ a ≤ N and
2 ≤ b ≤ N?

link: https://projecteuler.net/problem=29

Solution:

We can use the logarithm to calculate the number of distinct terms. If we take
the logarithm of the number, we get:

    log(a**b) = b*log(a)

So we can calculate the logarithm of all numbers in the range and then we can
count the number of distinct terms. It would be faster than raw calculation of
a**b, cause a**b grows much faster than b*log(a) and the number of distinct
terms is the same. One problem is that the logarithms has some precision error,
so with the higher N, we can get the error in the result
"""
from math import log2


def straight_solution(N):
    return len({a**b for a in (range(2, N+1)) for b in range(2, N+1)})


def solution(N):
    return len({b*log2(a) for a in (range(2, N+1)) for b in range(2, N+1)})


# test
if __name__ == '__main__':
    print(straight_solution(5))  # 15
    print(straight_solution(100))  # 9183

    print(solution(5))  # 15
    print(solution(100))  # 9183
